name: Deploy App to Heroku Server
on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build Frontend
        run: |
          cd frontend
          yarn install
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-Build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-Build
          path: backend/src/main/resources/static
      - name: Build with maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/app.jar

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: production-heroku
      url: https://saleio.herokuapp.com/
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: target
      - name: Login to Heroku
        run: heroku container:login
      - name: Push docker container
        run: heroku container:push web -a saleio
      - name: Deploy docker container
        run: heroku container:release web -a saleio
      - name: Connect to postgres DB
        run: heroku pg:psql postgresql-pointy-54122 --app saleio
